# Переменные, которые можно использовать в этом же конфигурационном файле.
# Итоговый конфигурационный файл шаблонизируется при помощи Jinja2
variables:
    purpose: '...Назначение проекта...'
    database: '...имя_бд...'
    home_path: '...домашний_каталог_проекта...'
    home_path_src: '...корневой_каталог_исходников...'

    instance_name: '...имя_инстанса...'

    # Fully qualified domain name. По умолчанию вычисляется как DNS-имя текущей машины.
    # Для работы по ip можно задать значение '{{ host_ip }}'
    host_fqdn: 'localhost'
    # Домашняя директория, относительно которой хранятся все данные сервисов.
    # Используется только в конфигурационном файле.
    http_port: ...порт_для_инстанса...
    https_port: 443
    protocol: 'http'


# Paths to product builds and product build versions.
# A version can be specified partially or not specified at all. If the version is not specified, it is determined as the last one.
# Predetermined variable {{ local_builds_path }} contains the path to the local builds "./etc/_builds/"
builds:
    # Platform bulds
    platform_builds:
        version: # auto
        path: '{{ local_builds_path }}/PlatformBuilds'
    # DBConverter builds
    dbconverter_builds:
        version: # auto
        path: '{{ local_builds_path }}/DBConverter'
    # Encryptor builds
    encryptor_builds:
        version: # auto
        path: '{{ local_builds_path }}/Encryptor'
    # CertificateTool builds
    certificate_tool_builds:
        version: # auto
        path: '{{ local_builds_path }}/CertificateTool'
    # Redistributable package builds
    redist_builds:
        version: # auto
        path: '{{ local_builds_path }}/Redist'
logs_path: &logs
    LOGS_PATH: 'C:\rx_logs\{{ instance_name }}'
common_config: &base
    <<: *logs
    # Unique identifier of the system. It is issued upon the first system delivery and used in barcode generation.
    # The parameter value must be specified within the first installation.
    PRIMARY_TENANT: 'Local'
    QUEUE_CONNECTION_STRING: 'virtualhost=...виртуальный_хост...;hostname=...имя_сервера...;port=5672;username=...логин...;password=...пароль...;Exchange=RX42_Exchange_{{ instance_name }}'
    # mssql
    DATABASE_ENGINE: 'mssql'
    CONNECTION_STRING: 'data source=...сервер...;initial catalog={{ database }};user id=...логин...;Password=...пароль...'
    # postgres
    #CONNECTION_STRING: 'server=...сервер...;port=...порт...;database={{ database }};user id=...логин...;Password=...пароль...'
    #DATABASE_ENGINE: 'postgres'
    DATA_PROTECTION_CERTIFICATE_FILE: '...путь_к_сертификату...'
    DATA_PROTECTION_CERTIFICATE_FILE_PASSWORD: '...пароль_сертификата...'
    WEB_HOST_PATH_BASE: 'Client'
    UTC_OFFSET: '4'
    AUTHENTICATION_USERNAME: 'Service User'
    AUTHENTICATION_PASSWORD: '11111'
    HYPERLINK_SERVER: 'http://{{ host_fqdn }}:{{ http_port }}/Sungero'
    MONGODB_CONNECTION_STRING: 'mongodb://<...user...>:<...password...>@<...HOST_IP...>:27017'
    LANGUAGE: 'ru-ru'
    LOG_LANGUAGE: 'ru-ru'

# Parameters of services and utilities.
# Command "all up" launches the services from the section below in the order they are listed, excluding third-party services such as RabbitMQ, Redis, and MongoDB.
services_config:
    SungeroWebServer: &SungeroWebServer
        <<: *base
        WEB_HOST_HTTP_PORT: # auto
        PREVIEW_ENABLED: 'true'
        PREVIEW_RELATIVE_PATH: '/Preview/'
        CENTRIFUGO_RELATIVE_PATH: '/Centrifugo/'
    SungeroWebClient:
        <<: *SungeroWebServer
        WEB_HOST_HTTP_PORT: # auto
    StorageService:
        <<: *base
        PORT: # auto
        STORAGE_PATH: '{{ home_path }}/storageservice'
    PreviewService:
        <<: *base
        PREVIEW_STORAGE_HOST: # auto
        TEMP_CONVERSION_FOLDER: '{{ home_path }}/previewservice/conversionresults'
        DOCUMENT_PROVIDER_CACHE_FOLDER: '{{ home_path }}/previewservice/sourcedocuments'
    PreviewStorage:
        <<: *base
        DEFAULT_SERVICE_PORT: # auto
        STORAGE_PATH: '{{ home_path }}/previewstorage'
    WorkflowProcessService:
        <<: *base
    DelayedOperationsService:
        <<: *base
    JobScheduler:
        <<: *base
    GenericService:
        <<: *base
        WORKER_SERVICE_ENABLED: true
        WORKFLOW_BLOCK_SERVICE_ENABLED: true
        REPORT_SERVICE_ENABLED: true
        WIDGET_SERVICE_ENABLED: true

        # WidgetsService settings
        # SungeroWorker settings
        # ReportService settings
        # WorkflowBlockService settings
    ClientsConnectionService:
        <<: *base
        QUEUE_RESPONSE_TIMEOUT: '00:00:30'
        SERVICE_PORT: # auto
        CENTRIFUGO_API_URI: # auto
        CENTRIFUGO_API_KEY: '...ключ_доступа_к_api_centrifugo...'
    SungeroCentrifugo:
        # Enables the "offset" field for the client-server protocol. We recommend you to leave this parameter enabled.
        'v3_use_offset': true
        # Access key for the Centrifugo API.  the Directum RX installation. It must be the same as the value of the CENTRIFUGO_API_KEY parameter of the Client Connections Service.
        'api_key': '...ключ_доступа_к_api_centrifugo...'
        # Port for all endpoints. The port number must be the same as in the Centrifugo address specified in the CENTRIFUGO_API_URI parameter of the Client Connections Service.
        'port': # auto
        # Authorization proxy endpoint. The default value is http://clientsconnectionservice:15672/authorize
        'proxy_connect_endpoint': #auto
        # Timeout for authorization proxying (in seconds).
        'proxy_connect_timeout': 5
        # Server subscription to a personal user channel.
        'user_subscribe_to_personal': true
        # Token generation secret.
        #'admin_secret': ''
    IntegrationService:
        <<: *base
        WEB_HOST_HTTP_PORT: # auto
    LogService:
        <<: *base
        PORT: # auto
    SungeroHaproxy:
        haproxy_config: 'etc\haproxy.cfg'
        # Path to the PEM certificate file.
        ssl_cert: ''
        http_port: '{{ http_port }}'
        https_port: '{{ https_port }}'
    IIS:
        site_name: 'DirectumRX Web Site'
        http_port: '{{ http_port }}'
        https_port: '{{ https_port }}'
        ssl_cert_thumbprint: ''
    ServiceRunner:
        <<: *logs
        CONFIGS_PATH:  # auto
        PACKAGES_ZIP_PATH: # auto
        PACKAGES_BIN_PATH: # auto
        SERVICE_RUNNER_PORT: # auto
    DeploymentTool:
        <<: *logs
        WEB_RELATIVE_PATH: 'Client'
        SERVER_HTTPS_PORT: '{{ https_port }}'
        SERVER_HTTP_PORT: '{{ http_port }}'
        SERVER_ROOT: '{{ host_fqdn }}'
        WEB_PROTOCOL: '{{ protocol }}'
    DeploymentToolUI:
        <<: *base
        WEB_RELATIVE_PATH: 'Client'
        SERVER_HTTPS_PORT: '{{ https_port }}'
        SERVER_HTTP_PORT: '{{ http_port }}'
        SERVER_ROOT: '{{ host_fqdn }}'
        WEB_PROTOCOL: '{{ protocol }}'
    DevelopmentStudio:
        <<: *base
        COMPANY_CODE: '...код_компании_разработчика...'
        SYSTEM_NAME: 'Develop'
        LOCAL_WEB_RELATIVE_PATH: 'Client'
        UNIQUE_NAMES_IN_OVERRIDES: true
        LOCAL_WEB_PROTOCOL: 'http'
        LOCAL_SERVER_HTTP_PORT: '{{ http_port }}'
        GIT_ROOT_DIRECTORY: '{{ home_path_src }}'
        REPOSITORIES:
            repository:
            -   '@folderName': 'Work'
                '@solutionType': 'Work'
                '@url': ''
            -   '@folderName': 'Box'
                '@solutionType': 'Base'
                '@url': ''
        SERVICE_RUNNER_CONFIG_PATH: '...корневой_каталог_инстанса_rx...\etc\_{{ instance_name }}\_services_config\ServiceRunner\_ConfigSettings.xml'

manage_applied_projects:
    postgresql_bin: 'C:\Program Files\PostgreSQL\14\bin'
    run_dds_after_set_project: 'true'
