# This is a basic workflow that is manually triggered

name: release-1

on: 
  push:
    tags:
    - '*'      

jobs:
  zip-files:
    runs-on: ubuntu-latest
    permissions:
      contents: write    
    steps:
      - uses: actions/checkout@v2

      - name: Update version
        uses: brettdorrans/write-version-to-file@master
        with:
          filename: 'src/ManageAppProjects/manifest.json'
          placeholder: '${VERSION}'

      - name: Create zip
        uses: papeloto/action-zip@v1
        with:
          files: src/ManageAppProjects ManageAppliedProjects.md
          dest: ManageAppProjects.zip
          recursive: true

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "ManageAppProjects.zip"
          bodyFile: 'readme.md'
          token: ${{ secrets.GITHUB_TOKEN }}          
